Us/06 cadastro equipamentos
fga-eps-mds/2022-2-Alectrion-EquipamentApi pull request #6
Opened 2023-01-17 14:41 UTC by Yagoas

## Modificações
Unidade de cadastro de equipamento incluída
## Descrição
Divisão de Suporte Técnico em Informática foi incluída como nova unidade / Refatoração
## US 06: cadastro equipamentos
## Como foi testado?
Foram testadas em tempo real de acordo com as mudanças no aplicativo

## Tipo de modificações
- [x] _ ​​correção de bug_

## Lista de controle:
- [x] Meu código segue a folha de estilos implementada
- [x] Meu _commits_ segue a política de commits do repo.

2023-01-22 18:17 UTC, ErickGiffoni requested changes
Bom trabalho. Apenas faça as mudanças mencionadas, depois teste o sistema por completo para ver se não deu nenhum bug etc, e peça a revisão novamente.

2023-01-22 18:17 UTC, ErickGiffoni commented on src/db/entities/equipment.ts
> +import { Situação } from '../../domain/entities/equipamentEnum/status'
Como comentado no PR do frontend, não usar acentuação para nomes de arquivos, variáveis, "chaves" etc.

Apenas coisas visíveis ao usuário, ou seja, coisas que vão pra interface gráfica, devem usar a acentuação de acordo com a gramática

2023-01-22 18:17 UTC, ErickGiffoni commented on src/db/entities/equipment.ts
> +  situação: Situação
```suggestion
  situacao: Situação
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/domain/entities/equipamentEnum/status.ts
> +export enum Situação {
```suggestion
export enum Situacao {
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/db/entities/equipment.ts
> +import { Situação } from '../../domain/entities/equipamentEnum/status'
```suggestion
import { Situacao } from '../../domain/entities/equipamentEnum/status'
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/domain/entities/equipment.ts
> +import { Situação } from './equipamentEnum/status'
```suggestion
import { Situacao } from './equipamentEnum/status'
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/domain/entities/equipment.ts
> +  situação: Situação
```suggestion
  situacao: Situação
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/presentation/controller/createEquipmentController.ts
> +  situação: string
```suggestion
  situacao: string
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/repository/equipment/update-equipment.ts
> +import { Situação } from '../../domain/entities/equipamentEnum/status'
```suggestion
import { Situacao } from '../../domain/entities/equipamentEnum/status'
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/repository/equipment/update-equipment.ts
> +  situação?: Situação
```suggestion
  situacao?: Situação
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/useCases/create-order-service/create-order-service.ts
> +import { Situação } from '../../domain/entities/equipamentEnum/status'
```suggestion
import { Situacao } from '../../domain/entities/equipamentEnum/status'
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/useCases/create-order-service/create-order-service.ts
> +        situação: Situação.Manutenção
```suggestion
        situacao: Situacao.Manutenção
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/useCases/createEquipment/createEquipmentUseCase.ts
> +import { Situação } from '../../domain/entities/equipamentEnum/status'
```suggestion
import { Situacao } from '../../domain/entities/equipamentEnum/status'
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/useCases/createEquipment/createEquipmentUseCase.ts
> +      (equipmentData.situação as Situação) ?? ('Reserva Técnica' as Situação)
```suggestion
      (equipmentData.situacao as Situacao) ?? ('Reserva Técnica' as Situacao)
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/useCases/find-order-service/find-order-service.ts
> +  situação: string
```suggestion
  situacao: string
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/useCases/find-order-service/find-order-service.ts
> +        situação: query.situação
```suggestion
        situacao: query.situacao
```

2023-01-22 18:17 UTC, ErickGiffoni commented on src/useCases/findUnit/findAllUnitUseCase.ts
> +import { Unit } from "../../domain/entities/unit";
Cara, esse arquivo pode retirar do commit. Parece que foi só teu estilizador que resolveu colocar aspas e ponto e vírgula nos lugares etc kkk
Melhor não.

2023-01-22 18:17 UTC, ErickGiffoni commented on src/useCases/getEquipment/getEquipmentUseCase.ts
> +  situação?: string
```suggestion
  situacao?: string
```

2023-01-22 18:38 UTC, Yagoas commented on src/useCases/findUnit/findAllUnitUseCase.ts
> +import { Unit } from "../../domain/entities/unit";
Por algum erro estávamos tentando commitar o arquivo como o original, na minha máquina estava aparecendo com o ponto e vírgula como se na main estivesse assim, aí havia alterado aqui para ficar correto só q commitou o arquivo diferente, desconsidera que foi algum bug.

2023-01-22 19:06 UTC, Yagoas commented
> 

Alterações feitas.

2023-01-23 14:52 UTC, AlineLermen approved these changes

2023-01-23 14:52 UTC, merged