Us/07 cadastro de ordem de serviço
fga-eps-mds/2022-2-Alectrion-EquipamentApi pull request #9
Opened 2023-01-21 01:51 UTC by JoaoVitorFarias

## Modificações
- Atualização do cadastro de ordem de serviço
- Atualização do eslint
- Correção do erro ao atualizar status de equipamento

## Descrição
Atualização do cadastro de movimentação e adição do endpoint para atualizar ordem de serviço

## _Issue_ relacionado
#16

## Motivação e Contexto
O cadastro não estava funcionando corretamente e havia a necessidade de atualizar as ordens de serviço

## Como foi testado?
Testado localmente

## Tipo de modificações
- [x] _ ​​correção de bug_
- [x] Nova _feature_

## Lista de controle:
- [x] Meu código segue a folha de estilos implementada
- [x] Meu _commits_ segue a política de commits do repo.
- [x] Adicionei testes para cobrir minhas modificações.
- [x] Todos os testes foram aprovados.

2023-01-22 18:31 UTC, ErickGiffoni requested changes
Conseguem corrigir os testes antes da gente aprovar ?

2023-01-28 15:33 UTC, ErickGiffoni commented
@JoaoVitorFarias não esqueça dos conflitos ok ?

2023-01-28 22:08 UTC, ErickGiffoni requested changes
Está quase lá ! @JoaoVitorFarias @CarlosEduardoMendesdeMesquita @mathonaut 
Falta só um teste passar
E se for o caso atualizem com a dev novamente

2023-01-30 16:46 UTC, ErickGiffoni commented on src/useCases/create-order-service/create-order-service.ts
> +        status: ('MAINTENANCE' as OStatus),
Não seria isso
```suggestion
        status: OStatus.MAINTENANCE,
```
?

2023-01-30 16:50 UTC, ErickGiffoni commented on tests/create-order-service-controller.spec.ts
> +  status: ('MAINTENANCE' as OSStatus),
```suggestion
  status: OSStatus.MAINTENANCE,
```
Assim pode não ?

2023-01-30 16:51 UTC, ErickGiffoni commented on tests/find-orders-service.spec.ts
> +  status: OSStatus.MAINTENANCE,
Aqui parece que funcionou

2023-01-30 16:58 UTC, JoaoVitorFarias commented on src/useCases/create-order-service/create-order-service.ts
> +        status: ('MAINTENANCE' as OStatus),
não, é dessa forma mesmo. No banco está registrado o enum, não o valor de cada enum. Então o certo é passar 'MAINTENANCE' em vez de 'Em manutenção', mas isso pode ser alterado posteriormente.

2023-01-30 18:49 UTC, ErickGiffoni commented on src/useCases/create-order-service/create-order-service.ts
> +        status: ('MAINTENANCE' as OStatus),
Saquei, boa !

2023-01-30 18:50 UTC, ErickGiffoni approved these changes

2023-01-30 23:37 UTC, merged